### ISSUE TITLE
Problems with OnOptionsChange() and Onchange() in Data Manipulation Plugin

### ISSUE THREAD

**Issue by dgiaquinta92** [VolkovLabs/volkovlabs-form-panel#338]
Hello! First of all, thank you very much for all the work. I use the plugins a lot and they are super useful.
I've been trying for a few days to create a form that updates all the fields according to the options I choose beforehand.

For example, I have a custom select with options, which retrieves data from an API. And I would like that when I choose one of these options, the value of the element updates so that I can update the next field.

I've tried using OnOptionsChange() and OnChange(), but Grafana gives me an error.
I've followed the example on the website.

Is it possible to do what I want? Or maybe I'm mistaken.

I use version 3.6.0 of the plugin and version 9.3.4 of Grafana.

Regards.

**Comment by mikhail-vl** [comment]
@dgiaquinta92 What is the error do you see? There is a new Change Handler option introduced in v3.5.0, which we have not documented yet. It was introduced for inter element updates. Have you tried to use it?

**Comment by dgiaquinta92** [comment]
Thank you for your response.
When I add the code and press submit, where it executes the onOptionsChange, the window automatically turns black and returns the following error:
`An unexpected error happened
Detalles
TypeError: Cannot read properties of undefined (reading 'layout')

    at Kn (https://*************/public/build/DashboardPage.83746403e354ba80cece.js:135:4496)
    at div
    at div
    at Ii (https://*************/public/build/DashboardPage.83746403e354ba80cece.js:258:27)
    at div
    at n (https://*************/public/build/DashboardPage.83746403e354ba80cece.js:37:6451)
    at div
    at n (https://*************/public/build/DashboardPage.83746403e354ba80cece.js:37:8400)
    at _t (https://*************/public/build/DashboardPage.83746403e354ba80cece.js:37:13987)
    at div
    at div
    at div
    at b (https://*************/public/build/2362.97a60cb324cdf48dbcc2.js:5799:1143)
    at ya (https://*************/public/build/DashboardPage.83746403e354ba80cece.js:381:1376)
    at g (https://*************/public/build/4743.1a1d46bf2371bc56aa60.js:2:1042468)
    at WithTheme(Connect(ya))
    at Er (https://*************/public/build/DashboardPage.83746403e354ba80cece.js:504:7179)
    at DashboardPage
    at g (https://*************/public/build/4743.1a1d46bf2371bc56aa60.js:2:1042468)
    at Suspense
    at c (https://*************/public/build/2362.97a60cb324cdf48dbcc2.js:1207:301)
    at _c (https://*************/public/build/2362.97a60cb324cdf48dbcc2.js:8831:350)
    at t (https://*************/public/build/4743.1a1d46bf2371bc56aa60.js:2:1060861)
    at t (https://*************/public/build/4743.1a1d46bf2371bc56aa60.js:2:1062882)
    at main
    at Cd (https://*************/public/build/2362.97a60cb324cdf48dbcc2.js:8792:6822)
    at t (https://*************/public/build/4743.1a1d46bf2371bc56aa60.js:2:1057479)
    at div
    at o (https://*************/public/build/2362.97a60cb324cdf48dbcc2.js:1996:4308)
    at t.KBarProvider (https://*************/public/build/4743.1a1d46bf2371bc56aa60.js:2:271053)
    at l (https://*************/public/build/2362.97a60cb324cdf48dbcc2.js:6143:19538)
    at c (https://*************/public/build/2362.97a60cb324cdf48dbcc2.js:1207:301)
    at u (https://*************/public/build/2362.97a60cb324cdf48dbcc2.js:1207:855)
    at l (https://*************/public/build/4743.1a1d46bf2371bc56aa60.js:2:1040513)
    at Su (https://*************/public/build/2362.97a60cb324cdf48dbcc2.js:8844:115)`

I have tried in several versions and environments.

Thank you
